```{r}
#library management
library(tidyverse)
library(tidymodels)
library(readxl)
library(ggrepel)
library(gridExtra)
library(mgcv)
```

```{r}
#base dataframe / to be updated with more data as needed. For now using 2019 data from big ten only
#B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
#bigten <- B1G_Baseball_Data_2019
```

```{r}
#new dataframe management
pitchdata <- data %>% select(EventID, BatSide, Balls, Strikes, PitchType, PitchX, PitchY, PitchSide, Delivery, PitchResult)
swingdata <- pitchdata %>% filter(PitchResult == "Foul" | PitchResult == "Bip" | PitchResult == "StrikeSwinging")

swingdata <- swingdata %>% mutate(Contact = ifelse(PitchResult == "Bip" | PitchResult == "Foul", "Contact", "whiff"),
                                  Contact = as.factor(case_when(
    Contact == "Contact" ~ "Contact",
    Contact == "whiff" ~ "whiff"))) %>%
mutate_at(7, as.numeric) %>% na.omit()

swingdata <- swingdata %>% mutate(
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0))

swingdata <- swingdata %>% mutate(PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0),
                                  contactbinary = ifelse(Contact == "whiff", 0, 1))
```

```{r}
set.seed(1234)
contact_split <- initial_split(swingdata, prop = .8)
contact_train <- training(contact_split)
contact_test <- testing(contact_split)

model_recipe <- 
  recipe(Contact ~ ., data = contact_train) %>% 
   update_role(EventID, contactbinary, PitchType, PitchResult, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```

```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_contactprob <- 
  rf_workflow %>% 
  fit(data = contact_train)
```

```{r}
rfpredict <- rf_fit_contactprob %>% predict(new_data = contact_train) %>%
  bind_cols(contact_train) 

rfpredict <- rf_fit_contactprob %>% predict(new_data = contact_train, type="prob") %>%
  bind_cols(rfpredict)
```

```{r}
metrics(rfpredict, Contact, .pred_class)
```

```{r}
rftestpredict <- rf_fit_contactprob %>% predict(new_data = contact_test) %>%
  bind_cols(contact_test)

rftestpredict <- rf_fit_contactprob %>% predict(new_data = contact_test, type="prob") %>%
  bind_cols(rftestpredict)

metrics(rftestpredict, Contact, .pred_class)
```


```{r}
rftestpredict %>%
  conf_mat(Contact, .pred_class)
```

```{r}
rfpredict %>%
arrange(.pred_Contact) %>%
ggplot(aes(x = .pred_Contact, y = contactbinary)) +
scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1)) +
scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1)) +
geom_smooth(aes(x = .pred_Contact, y = contactbinary), color = "red", se = F, method = "loess") + 
# you can use stat_smooth in place of geom_smooth
geom_abline()
```