```{r}
# this code wont run except added to the end of strikeprobability.rmd
do_fit <- function(d){
  require(mgcv)
  gam(Strike ~ s(PitchX, PitchY),
      family=binomial, 
      data=d)
}

##### function cplot()
##### predict and plot over grid
##### assuming gam fit stored in variable fit

cplot <- function(){
df_p <- expand.grid(PitchX = seq(-1.2, 1.2, length=50),
                    PitchY = seq(1, 4, length=50))
df_p$lp <- predict(fit, df_p)
df_p$Probability <- exp(df_p$lp) / (1 + exp(df_p$lp))

topKzone <- 3.5
botKzone <- 1.6
inKzone <- -0.85
outKzone <- 0.85
kZone <- data.frame(
  x=c(inKzone, inKzone, outKzone, outKzone, inKzone),
  y=c(botKzone, topKzone, topKzone, botKzone, botKzone)
)
ggplot(df_p)  +
  stat_contour(aes(x=PitchX, y=PitchY, 
                   z=Probability,
                   color = ..level..),
               breaks=c(.5, .9),
               size=1.5) +
  geom_path(aes(x, y), data=kZone, 
            lwd=1, col="red") +
  xlim(-1.5, 1.5) +
  ylim(1.0, 4.0)  + 
  theme(
    plot.title = element_text(
      colour = "blue",
      size = 16,
      hjust = 0.5,
      vjust = 0.8,
      angle = 0
    )
  ) + coord_fixed(ratio = 1)
}

##################################

# basic plot

fit <- do_fit(filter(pitchestaken,
                     BatSide == "R"))
p1 <- cplot() + ggtitle("Batting Right")

fit <- do_fit(filter(pitchestaken,
                     BatSide == "L"))
p2 <- cplot() + ggtitle("Batting Left")
grid.arrange(p1, p2, ncol=2)

```

```{r}
# look at number of strikes effect

fit <- do_fit(filter(pitchestaken,
                     BatSide == "R",
                     Strikes == 0))
p1 <- cplot() + ggtitle("Right, 0 Strikes")

fit <- do_fit(filter(pitchestaken,
                     BatSide == "R",
                     Strikes == 2))
p2 <- cplot() + ggtitle("Right, 2 Strikes")

fit <- do_fit(filter(pitchestaken,
                     BatSide == "R",
                     Balls == 0))

p3 <- cplot() + ggtitle("Right, 0 Balls")

fit <- do_fit(filter(pitchestaken,
                     BatSide == "R",
                     Balls == 3))
p4 <- cplot() + ggtitle("Right, 3 Balls")

grid.arrange(p1, p2, p3, p4, 
             top="True Strike Zones - 2019 Data ")
```