```{r}
#library management
library(tidyverse)
library(tidymodels)
library(readxl)
library(ggrepel)
library(gridExtra)
library(mgcv)
```

```{r}
B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
bigten <- B1G_Baseball_Data_2019
bip <- bigten %>% filter(PitchResult == "Bip" & Contact != "NA")
bip <- bip %>% mutate(PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0),
                      Contact_Binary = as.factor(case_when(
    Contact == "Hard" ~ "Hard",
    Contact == "Soft" ~ "Soft",
    Contact == "Medium" ~ "Medium")))
```

```{r}
model_bip <- bip %>% select(EventID, PitchType_Binary, PitchX, PitchY, Contact_Binary, BatSide, PitchSide, Delivery) %>% mutate_at(3:4, as.numeric) %>% na.omit()

model_bip <- model_bip %>% mutate(
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0))
```

```{r}
set.seed(1234)
pitches_split <- initial_split(model_bip, prop = .8)
pitches_train <- training(pitches_split)
pitches_test <- testing(pitches_split)

model_recipe <- 
  recipe(Contact_Binary ~ ., data = pitches_train) %>% 
  update_role(EventID, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```

```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_hardhitprob <- 
  rf_workflow %>% 
  fit(data = pitches_train)
```



```{r}
#base dataframe / to be updated with more data as needed. For now using 2019 data from big ten only
B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
bigten <- B1G_Baseball_Data_2019
```

```{r}
#new dataframe management
endpa <- bigten %>% filter(LastPA == 1)
batters <- endpa %>% group_by(Batter)
pitchdata <- bigten %>% select(EventID, BatSide, Balls, Strikes, PitchType, PitchX, PitchY, PitchSide, Delivery, PitchResult)
# interested specifically in pitches the umpire made a call on. Don't care about BIP
pitchestaken <- pitchdata %>% filter(PitchResult == "Ball" | PitchResult == "StrikeTaken")
pitchestaken <- pitchestaken %>% mutate(PitchResult = ifelse(PitchResult == "StrikeTaken", "Strike", "Ball"),
                                          Strike = ifelse(PitchResult == "Strike", 1,0),
                                        Ball = ifelse(PitchResult == "Ball",1,0),
                                        PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0)) %>%
  mutate_at(6:7, as.numeric) %>% na.omit

pitchestaken <- pitchestaken %>% mutate(
  PitchResult = as.factor(case_when(
    PitchResult == "Strike" ~ "Strike",
    PitchResult == "Ball" ~ "Ball")),
    
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0)) %>% na.omit()
```

```{r}
# splitting into testing and training data to more rigorously examine the model
set.seed(1234)
pitches_split <- initial_split(pitchestaken, prop = .8)
pitches_train <- training(pitches_split)
pitches_test <- testing(pitches_split)


model_recipe <- 
  recipe(PitchResult ~ ., data = pitches_train) %>% 
  update_role(EventID, PitchType, Strike, Ball, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```
```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_strikeprob <- 
  rf_workflow %>% 
  fit(data = pitches_train)
```

```{r}
rfpredict <- rf_fit_strikeprob %>% predict(new_data = pitches_train) %>%
  bind_cols(pitches_train) 

rfpredict <- rf_fit_strikeprob %>% predict(new_data = pitches_train, type="prob") %>%
  bind_cols(rfpredict)
```

```{r}
#base dataframe / to be updated with more data as needed. For now using 2019 data from big ten only
B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
bigten <- B1G_Baseball_Data_2019
```

```{r}
#new dataframe management
endpa <- bigten %>% filter(LastPA == 1)
batters <- endpa %>% group_by(Batter)
pitchdata <- bigten %>% select(EventID, BatSide, Balls, Strikes, PitchType, PitchX, PitchY, PitchSide, Delivery, PitchResult)
swingpitchdata <- pitchdata %>% mutate(swing = ifelse(PitchResult == "Foul" | PitchResult == "StrikeSwinging" | PitchResult == "Bip", "Swing", "Take"),
                                  swingbinary = ifelse(PitchResult == "Foul" | PitchResult == "StrikeSwinging" | PitchResult == "Bip", 1, 0),
                                  PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0),
                                  swing = as.factor(case_when(
    swing == "Swing" ~ "Swing",
    swing == "Take" ~ "Take"))) %>% mutate_at(6:7, as.numeric) %>% na.omit
```

```{r}
model_swing <- swingpitchdata %>% select(EventID, PitchType_Binary, PitchX, PitchY, swing, BatSide, PitchSide, Delivery) %>% mutate_at(3:4, as.numeric) %>% na.omit()

model_swing <- model_swing %>% mutate(
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0))
```

```{r}
set.seed(1234)
pitches_split <- initial_split(model_swing, prop = .8)
pitches_train <- training(pitches_split)
pitches_test <- testing(pitches_split)

model_recipe <- 
  recipe(swing ~ ., data = pitches_train) %>% 
  update_role(EventID, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```

```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_swingprob <- 
  rf_workflow %>% 
  fit(data = pitches_train)
```

```{r}
rfpredict <- rf_fit_swingprob %>% predict(new_data = pitches_train) %>%
  bind_cols(pitches_train) 

rfpredict <- rf_fit_swingprob %>% predict(new_data = pitches_train, type="prob") %>%
  bind_cols(rfpredict)
```

```{r}
#base dataframe / to be updated with more data as needed. For now using 2019 data from big ten only
B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
bigten <- B1G_Baseball_Data_2019
```

```{r}
#new dataframe management
pitchdata <- bigten %>% select(EventID, BatSide, Balls, Strikes, PitchType, PitchX, PitchY, PitchSide, Delivery, PitchResult)
swingdata <- pitchdata %>% filter(PitchResult == "Foul" | PitchResult == "Bip" | PitchResult == "StrikeSwinging")

swingdata <- swingdata %>% mutate(Contact = ifelse(PitchResult == "Bip" | PitchResult == "Foul", "Contact", "whiff"),
                                  Contact = as.factor(case_when(
    Contact == "Contact" ~ "Contact",
    Contact == "whiff" ~ "whiff"))) %>%
mutate_at(7, as.numeric) %>% na.omit()

swingdata <- swingdata %>% mutate(
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0))

swingdata <- swingdata %>% mutate(PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0))
```

```{r}
set.seed(1234)
contact_split <- initial_split(swingdata, prop = .8)
contact_train <- training(contact_split)
contact_test <- testing(contact_split)

model_recipe <- 
  recipe(Contact ~ ., data = contact_train) %>% 
   update_role(EventID, PitchType, PitchResult, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```

```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_contactprob <- 
  rf_workflow %>% 
  fit(data = contact_train)
```

```{r}
rfpredict <- rf_fit_contactprob %>% predict(new_data = contact_train) %>%
  bind_cols(contact_train) 

rfpredict <- rf_fit_contactprob %>% predict(new_data = contact_train, type="prob") %>%
  bind_cols(rfpredict)
```