```{r}
#library management
library(tidyverse)
library(tidymodels)
library(readxl)
library(ggrepel)
library(gridExtra)
library(mgcv)
```

```{r}
#base dataframe / to be updated with more data as needed. For now using 2019 data from big ten only
#B1G_Baseball_Data_2019 <- read_excel("~/B1G Baseball Data 2019.xlsx")
#bigten <- B1G_Baseball_Data_2019
```

```{r}
#new dataframe management
endpa <- data %>% filter(LastPA == 1)
batters <- endpa %>% group_by(Batter)
pitchdata <- data %>% select(EventID, BatSide, Balls, Strikes, PitchType, PitchX, PitchY, PitchSide, Delivery, PitchResult)
swingpitchdata <- pitchdata %>% mutate(swing = ifelse(PitchResult == "Foul" | PitchResult == "StrikeSwinging" | PitchResult == "Bip", "Swing", "Take"),
                                  swingbinary = ifelse(PitchResult == "Foul" | PitchResult == "StrikeSwinging" | PitchResult == "Bip", 1, 0),
                                  PitchType_Binary = ifelse(PitchType == "Fastball", 1, 0),
                                  swing = as.factor(case_when(
    swing == "Swing" ~ "Swing",
    swing == "Take" ~ "Take"))) %>% mutate_at(6:7, as.numeric) %>% na.omit
```

```{r}
model_swing <- swingpitchdata %>% select(EventID, PitchType_Binary, PitchX, PitchY, swing, BatSide, PitchSide, Delivery, swingbinary) %>% mutate_at(3:4, as.numeric) %>% na.omit()

model_swing <- model_swing %>% mutate(
    BatSide = ifelse(BatSide == "R", 1, 0),
    PitchSide = ifelse(PitchSide == "R", 1, 0),
    Delivery = ifelse(Delivery == "WindUp", 1, 0))
```

```{r}
set.seed(1234)
pitches_split <- initial_split(model_swing, prop = .8)
pitches_train <- training(pitches_split)
pitches_test <- testing(pitches_split)

model_recipe <- 
  recipe(swing ~ ., data = pitches_train) %>% 
  update_role(EventID, swingbinary, new_role = "ID") %>%
  step_normalize(all_predictors())

summary(model_recipe)
```

```{r}
rf_mod <- 
  rand_forest() %>% 
  set_engine("ranger") %>%
  set_mode("classification")
```

```{r}
rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(model_recipe)
```

```{r}
rf_fit_swingprob <- 
  rf_workflow %>% 
  fit(data = pitches_train)
```

```{r}
rfpredict <- rf_fit_swingprob %>% predict(new_data = pitches_train) %>%
  bind_cols(pitches_train) 

rfpredict <- rf_fit_swingprob %>% predict(new_data = pitches_train, type="prob") %>%
  bind_cols(rfpredict)
```

```{r}
metrics(rfpredict, swing, .pred_class)
```

```{r}
rftestpredict <- rf_fit_swingprob %>% predict(new_data = pitches_test) %>%
  bind_cols(pitches_test)

rftestpredict <- rf_fit_swingprob %>% predict(new_data = pitches_test, type="prob") %>%
  bind_cols(rftestpredict)

metrics(rftestpredict, swing, .pred_class)
```


```{r}
rftestpredict %>%
  conf_mat(swing, .pred_class)
```

```{r}
rfpredict %>%
arrange(.pred_Swing) %>%
ggplot(aes(x = .pred_Swing, y = swingbinary)) +
scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1)) +
scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1)) +
geom_smooth(aes(x = .pred_Swing, y = swingbinary), color = "red", se = F, method = "loess") + 
# you can use stat_smooth in place of geom_smooth
geom_abline()
```